// AUTO-GENERATED by scripts/codegen-events.py from
// services/agent/findevil_agent/events.py. DO NOT EDIT BY
// HAND — re-run the codegen instead. Per A3 plan Task 4.3.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AgentEvent =
  | ToolCallStart
  | ToolCallOutput
  | AgentMessage
  | Finding
  | VerifierAction
  | ChainUpdate
  | RunVerdict
  | PlanProposed
  | PlanApproved
  | HypothesisUpdate
  | ContradictionFound;
/**
 * UUID4 of the case this event belongs to
 */
export type CaseId = string;
export type EventId = string;
export type Ts = string;
export type EventType = "ToolCallStart";
export type ToolName = string;
export type ToolCallId = string;
export type InputHash = string;
export type Pool = ("A" | "B" | "shared") | null;
/**
 * UUID4 of the case this event belongs to
 */
export type CaseId1 = string;
export type EventId1 = string;
export type Ts1 = string;
export type EventType1 = "ToolCallOutput";
export type ToolCallId1 = string;
export type OutputHash = string;
export type RowCount = number | null;
export type SignatureBundle = string | null;
export type MerkleLeafIndex = number | null;
/**
 * UUID4 of the case this event belongs to
 */
export type CaseId2 = string;
export type EventId2 = string;
export type Ts2 = string;
export type EventType2 = "AgentMessage";
export type Role = "supervisor" | "pool_a" | "pool_b" | "judge" | "verifier" | "correlator";
export type Content = string;
/**
 * UUID4 of the case this event belongs to
 */
export type CaseId3 = string;
export type EventId3 = string;
export type Ts3 = string;
export type EventType3 = "Finding";
export type FindingId = string;
export type ToolCallId2 = string;
export type ArtifactPath = string;
export type ArtifactOffset = string | null;
export type Confidence = "CONFIRMED" | "INFERRED" | "HYPOTHESIS";
export type MitreTechnique = string | null;
export type Description = string;
export type PoolOrigin = ("A" | "B" | "merged") | null;
export type DerivedFrom = string[] | null;
/**
 * UUID4 of the PRIOR case this hit came from
 */
export type CaseId4 = string;
/**
 * UTC ISO-8601 (trailing Z) of the prior observation
 */
export type Ts4 = string;
/**
 * BM25 x recency-decayed recall confidence, 0.0-1.0
 */
export type Confidence1 = number;
export type PriorObservations = PriorObservation[];
/**
 * UUID4 of the case this event belongs to
 */
export type CaseId5 = string;
export type EventId4 = string;
export type Ts5 = string;
export type EventType4 = "VerifierAction";
export type Action = "approved" | "rejected" | "downgraded";
export type FindingId1 = string;
export type Reason = string;
/**
 * UUID4 of the case this event belongs to
 */
export type CaseId6 = string;
export type EventId5 = string;
export type Ts6 = string;
export type EventType5 = "ChainUpdate";
export type MerkleRoot = string;
export type LeafCount = number;
export type SignaturePending = boolean;
/**
 * UUID4 of the case this event belongs to
 */
export type CaseId7 = string;
export type EventId6 = string;
export type Ts7 = string;
export type EventType6 = "RunVerdict";
export type Verdict = "CONFIRMED_EVIL" | "SUSPICIOUS" | "BENIGN" | "INCONCLUSIVE";
export type ConfidenceScore = number;
export type FindingCount = number;
export type ManifestPath = string;
export type ManifestVerifyPath = string | null;
/**
 * UUID4 of the case this event belongs to
 */
export type CaseId8 = string;
export type EventId7 = string;
export type Ts8 = string;
export type EventType7 = "PlanProposed";
export type PlanSteps = string[];
export type EstimatedToolCalls = number;
/**
 * UUID4 of the case this event belongs to
 */
export type CaseId9 = string;
export type EventId8 = string;
export type Ts9 = string;
export type EventType8 = "PlanApproved";
export type ApprovedBy = "human" | "auto";
/**
 * UUID4 of the case this event belongs to
 */
export type CaseId10 = string;
export type EventId9 = string;
export type Ts10 = string;
export type EventType9 = "HypothesisUpdate";
export type Hypothesis = "persistence" | "exfiltration" | "both" | "neither";
export type Pool1 = "A" | "B";
export type ConfidenceDelta = number;
export type SupportingFindingIds = string[];
/**
 * UUID4 of the case this event belongs to
 */
export type CaseId11 = string;
export type EventId10 = string;
export type Ts11 = string;
export type EventType10 = "ContradictionFound";
export type ContradictionId = string;
export type PoolAClaim = string;
export type PoolBClaim = string;
export type ConflictingToolCallIds = string[];
export type ResolutionRequired = boolean;

export interface ToolCallStart {
  case_id: CaseId;
  event_id?: EventId;
  ts?: Ts;
  event_type?: EventType;
  tool_name: ToolName;
  tool_call_id: ToolCallId;
  input_hash: InputHash;
  pool?: Pool;
}
export interface ToolCallOutput {
  case_id: CaseId1;
  event_id?: EventId1;
  ts?: Ts1;
  event_type?: EventType1;
  tool_call_id: ToolCallId1;
  output_hash: OutputHash;
  row_count?: RowCount;
  signature_bundle?: SignatureBundle;
  merkle_leaf_index?: MerkleLeafIndex;
}
export interface AgentMessage {
  case_id: CaseId2;
  event_id?: EventId2;
  ts?: Ts2;
  event_type?: EventType2;
  role: Role;
  content: Content;
}
export interface Finding {
  case_id: CaseId3;
  event_id?: EventId3;
  ts?: Ts3;
  event_type?: EventType3;
  finding_id: FindingId;
  tool_call_id: ToolCallId2;
  artifact_path: ArtifactPath;
  artifact_offset?: ArtifactOffset;
  confidence: Confidence;
  mitre_technique?: MitreTechnique;
  description: Description;
  pool_origin?: PoolOrigin;
  derived_from?: DerivedFrom;
  prior_observations?: PriorObservations;
}
/**
 * A NON-evidentiary cross-case recall hit (Hermes ``memory_recall``).
 *
 * Rides on a :class:`Finding` as background context only. It deliberately
 * carries no ``tool_call_id``, ``value``, or ``sha256``: prior-case memory is
 * never current-case evidence (SOUL.md / PLAYBOOK.md §34), never satisfies the
 * >=2-artifact-class rule, and never becomes a Merkle leaf. ``extra="forbid"``
 * keeps an evidence handle from being smuggled in.
 */
export interface PriorObservation {
  case_id: CaseId4;
  ts: Ts4;
  confidence: Confidence1;
}
export interface VerifierAction {
  case_id: CaseId5;
  event_id?: EventId4;
  ts?: Ts5;
  event_type?: EventType4;
  action: Action;
  finding_id: FindingId1;
  reason: Reason;
}
export interface ChainUpdate {
  case_id: CaseId6;
  event_id?: EventId5;
  ts?: Ts6;
  event_type?: EventType5;
  merkle_root: MerkleRoot;
  leaf_count: LeafCount;
  signature_pending: SignaturePending;
}
export interface RunVerdict {
  case_id: CaseId7;
  event_id?: EventId6;
  ts?: Ts7;
  event_type?: EventType6;
  verdict: Verdict;
  confidence_score: ConfidenceScore;
  finding_count: FindingCount;
  manifest_path: ManifestPath;
  manifest_verify_path?: ManifestVerifyPath;
}
export interface PlanProposed {
  case_id: CaseId8;
  event_id?: EventId7;
  ts?: Ts8;
  event_type?: EventType7;
  plan_steps: PlanSteps;
  estimated_tool_calls: EstimatedToolCalls;
}
export interface PlanApproved {
  case_id: CaseId9;
  event_id?: EventId8;
  ts?: Ts9;
  event_type?: EventType8;
  approved_by: ApprovedBy;
}
export interface HypothesisUpdate {
  case_id: CaseId10;
  event_id?: EventId9;
  ts?: Ts10;
  event_type?: EventType9;
  hypothesis: Hypothesis;
  pool: Pool1;
  confidence_delta: ConfidenceDelta;
  supporting_finding_ids: SupportingFindingIds;
}
export interface ContradictionFound {
  case_id: CaseId11;
  event_id?: EventId10;
  ts?: Ts11;
  event_type?: EventType10;
  contradiction_id: ContradictionId;
  pool_a_claim: PoolAClaim;
  pool_b_claim: PoolBClaim;
  conflicting_tool_call_ids: ConflictingToolCallIds;
  resolution_required: ResolutionRequired;
}
