"""Stdio JSON-RPC client for the findevil-mcp Rust server.

Spec #2 §3 + §6. The Python agent spawns the Rust binary as a
subprocess and exchanges line-delimited JSON-RPC 2.0 requests over
stdin/stdout. Each ``call_tool(name, args)`` returns the tool's
typed output plus a SHA-256 of the raw output bytes — the latter
becomes a Merkle leaf for M2.

Design decisions:

  * Synchronous API. The agent runtime is mostly async but every
    LangGraph node is invoked from a sync context too; a sync
    client with internal threading is the simpler primitive.
    Async wrappers can be added in a follow-up.
  * ``McpClient`` is a Protocol; ``StdioMcpClient`` is the real
    impl; ``MockMcpClient`` is the test impl. Tests never spawn
    real binaries.
  * Tool-call IDs are UUID4 generated in the client. The server
    echoes them on responses so the audit trail can correlate.

Wire format (per MCP spec):

  Request line:   ``{"jsonrpc":"2.0","id":N,"method":"tools/call",
                     "params":{"name":TOOL,"arguments":{...}}}\\n``

  Response line:  ``{"jsonrpc":"2.0","id":N,"result":{
                     "content":[{"type":"text","text":STRINGIFIED_JSON}],
                     "_meta":{...}}}\\n``

  Error line:     ``{"jsonrpc":"2.0","id":N,"error":{
                     "code":N,"message":"...","data":{...}}}\\n``
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import subprocess
import threading
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol


class McpClientError(RuntimeError):
    """Generic client failure — pre-RPC-layer issues (subprocess
    crashed, JSON malformed, etc.)."""


class McpRpcError(RuntimeError):
    """Server returned a JSON-RPC error response. ``code`` and
    ``data`` come from the response envelope."""

    def __init__(self, code: int, message: str, data: Any | None = None) -> None:
        super().__init__(message)
        self.code = code
        self.data = data


@dataclass(frozen=True)
class ToolCallResult:
    """Outcome of a single ``call_tool``.

    ``raw_output_text`` is the verbatim ``content[0].text`` string
    the server emitted. ``parsed`` is its ``json.loads`` if it
    parses; otherwise None and the raw text remains the source of
    truth for the M2 layer.
    """

    tool_call_id: str
    """UUID4 generated by the client; quoted in audit log."""

    tool_name: str
    raw_output_text: str
    output_sha256: str
    parsed: dict[str, Any] | None
    meta: dict[str, Any] = field(default_factory=dict)
    """``_meta`` from the response envelope (Spec #2 §6 — MCP Apps
    widget pointers live here as ``_meta.ui.resourceUri``)."""

    wall_clock_ms: int = 0


class McpClient(Protocol):
    """The face the agent layer depends on."""

    def call_tool(self, tool_name: str, arguments: dict[str, Any]) -> ToolCallResult: ...

    def close(self) -> None: ...


# ---------------------------------------------------------------------------
# StdioMcpClient — spawns + drives the real Rust binary.
# ---------------------------------------------------------------------------


class StdioMcpClient:
    """Production client over stdio JSON-RPC.

    Usage:
        client = StdioMcpClient(["/usr/local/bin/findevil-mcp"])
        result = client.call_tool("evtx_query", {"case_id": "c", "evtx_path": "x"})
        client.close()

    Or via a context manager:
        with StdioMcpClient([...]) as client:
            ...
    """

    _next_id: int

    def __init__(
        self,
        command: list[str],
        *,
        cwd: Path | None = None,
        env: dict[str, str] | None = None,
        startup_timeout_s: float = 5.0,
        request_timeout_s: float = 120.0,
    ) -> None:
        self._command = list(command)
        self._cwd = cwd
        self._env = env
        self._startup_timeout_s = startup_timeout_s
        self._request_timeout_s = request_timeout_s
        self._proc: subprocess.Popen[str] | None = None
        self._lock = threading.Lock()
        self._next_id = 1
        self._closed = False

    # --- lifecycle ---

    def __enter__(self) -> StdioMcpClient:
        self._ensure_started()
        return self

    def __exit__(self, *_: object) -> None:
        self.close()

    def _ensure_started(self) -> None:
        if self._proc is not None:
            return
        try:
            self._proc = subprocess.Popen(
                self._command,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                cwd=str(self._cwd) if self._cwd else None,
                env=self._env,
                text=True,
                encoding="utf-8",
                bufsize=1,  # line-buffered
            )
        except FileNotFoundError as exc:
            raise McpClientError(f"could not spawn MCP server {self._command!r}: {exc}") from exc

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        if self._proc is None:
            return
        proc = self._proc
        try:
            if proc.stdin and not proc.stdin.closed:
                proc.stdin.close()
        except Exception:  # nosec - best effort
            pass
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
            with contextlib.suppress(subprocess.TimeoutExpired):
                proc.wait(timeout=5)

    # --- core call ---

    def call_tool(self, tool_name: str, arguments: dict[str, Any]) -> ToolCallResult:
        """Send one ``tools/call`` and parse the response.

        Thread-safe. Raises ``McpClientError`` on transport failure,
        ``McpRpcError`` on server-side error.
        """
        if self._closed:
            raise McpClientError("client is closed")
        with self._lock:
            self._ensure_started()
            assert self._proc is not None
            assert self._proc.stdin is not None
            assert self._proc.stdout is not None

            request_id = self._next_id
            self._next_id += 1
            tool_call_id = str(uuid.uuid4())
            request = {
                "jsonrpc": "2.0",
                "id": request_id,
                "method": "tools/call",
                "params": {"name": tool_name, "arguments": arguments},
            }
            line = json.dumps(request, separators=(",", ":")) + "\n"
            started = time.monotonic()
            try:
                self._proc.stdin.write(line)
                self._proc.stdin.flush()
            except (BrokenPipeError, OSError) as exc:
                raise McpClientError(f"MCP stdin write failed: {exc}") from exc

            response_line = self._read_line_with_timeout()
            wall_ms = int((time.monotonic() - started) * 1000)

            try:
                response = json.loads(response_line)
            except json.JSONDecodeError as exc:
                raise McpClientError(
                    f"MCP server returned non-JSON line: {response_line[:200]!r}"
                ) from exc

            return self._parse_response(
                response=response,
                tool_call_id=tool_call_id,
                tool_name=tool_name,
                wall_ms=wall_ms,
            )

    # --- helpers ---

    def _read_line_with_timeout(self) -> str:
        """Read a single line with a per-request wall-clock budget.

        We don't have signal-based timeouts on Windows; instead spawn
        the read on a thread and join. Cheap because each call only
        waits for one response line.
        """
        assert self._proc is not None
        assert self._proc.stdout is not None
        result: dict[str, str] = {}

        def reader() -> None:
            try:
                ln = self._proc.stdout.readline()  # type: ignore[union-attr]
                result["line"] = ln
            except Exception as exc:
                result["error"] = repr(exc)

        thread = threading.Thread(target=reader, daemon=True)
        thread.start()
        thread.join(timeout=self._request_timeout_s)
        if thread.is_alive():
            raise McpClientError(f"MCP request timed out after {self._request_timeout_s}s")
        if "error" in result:
            raise McpClientError(f"MCP read error: {result['error']}")
        line = result.get("line", "")
        if not line:
            raise McpClientError("MCP server closed stdout before responding")
        return line.rstrip("\r\n")

    def _parse_response(
        self,
        *,
        response: dict[str, Any],
        tool_call_id: str,
        tool_name: str,
        wall_ms: int,
    ) -> ToolCallResult:
        if "error" in response:
            err = response["error"]
            raise McpRpcError(
                code=int(err.get("code", -1)),
                message=str(err.get("message", "<no message>")),
                data=err.get("data"),
            )
        result = response.get("result") or {}
        content = result.get("content") or []
        text = ""
        if content and isinstance(content[0], dict):
            text = str(content[0].get("text", ""))
        meta = result.get("_meta") or {}
        sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
        parsed: dict[str, Any] | None = None
        try:
            obj = json.loads(text)
            if isinstance(obj, dict):
                parsed = obj
        except json.JSONDecodeError:
            parsed = None
        return ToolCallResult(
            tool_call_id=tool_call_id,
            tool_name=tool_name,
            raw_output_text=text,
            output_sha256=sha,
            parsed=parsed,
            meta=meta,
            wall_clock_ms=wall_ms,
        )


# ---------------------------------------------------------------------------
# MockMcpClient — used by tests.
# ---------------------------------------------------------------------------


class MockMcpClient:
    """Test client that returns canned responses keyed by tool name.

    ``register(tool_name, handler)`` accepts a callable
    ``(arguments) -> dict | str`` that produces the result. dicts
    get JSON-serialized; strings are returned verbatim.

    Records all calls in ``calls`` for assertion.
    """

    def __init__(self) -> None:
        self._handlers: dict[str, Any] = {}
        self.calls: list[tuple[str, dict[str, Any], ToolCallResult]] = []

    def register(self, tool_name: str, handler: Any) -> None:
        self._handlers[tool_name] = handler

    def call_tool(self, tool_name: str, arguments: dict[str, Any]) -> ToolCallResult:
        if tool_name not in self._handlers:
            raise McpRpcError(
                code=-32601,  # JSON-RPC method-not-found code
                message=f"mock has no handler registered for {tool_name!r}",
            )
        handler = self._handlers[tool_name]
        produced = handler(arguments) if callable(handler) else handler

        if isinstance(produced, dict):
            text = json.dumps(produced, sort_keys=True, separators=(",", ":"))
        elif isinstance(produced, str):
            text = produced
        else:
            text = json.dumps({"value": produced}, sort_keys=True, separators=(",", ":"))

        sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
        parsed: dict[str, Any] | None
        try:
            parsed_obj = json.loads(text)
            parsed = parsed_obj if isinstance(parsed_obj, dict) else None
        except json.JSONDecodeError:
            parsed = None

        result = ToolCallResult(
            tool_call_id=str(uuid.uuid4()),
            tool_name=tool_name,
            raw_output_text=text,
            output_sha256=sha,
            parsed=parsed,
            meta={},
            wall_clock_ms=0,
        )
        self.calls.append((tool_name, dict(arguments), result))
        return result

    def close(self) -> None:
        pass


__all__ = [
    "McpClient",
    "McpClientError",
    "McpRpcError",
    "MockMcpClient",
    "StdioMcpClient",
    "ToolCallResult",
]
