#!/usr/bin/env bash
# fetch-nist-fixture.sh — pull ONE small public Security.evtx for the
# real-evidence smoke harness.
#
# Why this exists separately from `fetch-fixtures.sh`:
#   `fetch-fixtures.sh` pulls the full 4.5 GB CFReDS Hacking Case +
#   the OTRF Mordor sparse clone. Useful for L3 goldens but too heavy
#   for a fast `--real-evidence` smoke loop on a developer laptop.
#   This script grabs ~1 small EVTX so `scripts/rust-mcp-smoke.py
#   --real-evidence` can drive `evtx_query` against real bytes in
#   under 30 seconds total.
#
# Source policy: NIST CFReDS distributes whole `.E01` images, not
# pre-extracted EVTX. Candidate small mirrors include:
#   * Atomic Red Team / OTRF Security-Datasets (small-subset .evtx)
#   * Internal team mirrors of CFReDS-extracted Security.evtx
# We don't pin a default URL because public EVTX URLs migrate often;
# operators set NIST_FIXTURE_URL + (optional) NIST_FIXTURE_SHA256.
# See `docs/DATASET.md` for current vetted candidates.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

DEST_DIR="${NIST_FIXTURE_DIR:-fixtures/single-evtx}"
DEST_FILE="${DEST_DIR}/Security.evtx"
PROV_FILE="${DEST_DIR}/PROVENANCE.txt"

log() { printf '[fetch-nist-fixture] %s\n' "$*" >&2; }

if [[ -z "${NIST_FIXTURE_URL:-}" ]]; then
  cat >&2 <<EOF
[fetch-nist-fixture] NIST_FIXTURE_URL is not set.

This script pulls ONE small Security.evtx for the real-evidence smoke
harness. Set NIST_FIXTURE_URL to a public mirror of a small Security.evtx,
e.g. an OTRF Security-Datasets sample or an internal CFReDS extract.

Optional: NIST_FIXTURE_SHA256 to pin the expected hash (recorded on
first pull if unset).

See docs/DATASET.md for current vetted candidates.

Example:
  NIST_FIXTURE_URL=https://example.org/path/to/Security.evtx \\
  NIST_FIXTURE_SHA256=<64-hex> \\
  bash scripts/fetch-nist-fixture.sh
EOF
  exit 2
fi

mkdir -p "${DEST_DIR}"

if [[ -f "${DEST_FILE}" ]]; then
  actual_sha="$(sha256sum "${DEST_FILE}" | awk '{print $1}')"
  if [[ -n "${NIST_FIXTURE_SHA256:-}" ]] && [[ "${actual_sha}" == "${NIST_FIXTURE_SHA256}" ]]; then
    log "ok: ${DEST_FILE} (cached, sha verified)"
    exit 0
  fi
  if [[ -z "${NIST_FIXTURE_SHA256:-}" ]] && grep -q "${actual_sha}" "${PROV_FILE}" 2>/dev/null; then
    log "ok: ${DEST_FILE} (cached, sha matches recorded provenance)"
    exit 0
  fi
  log "existing fixture sha=${actual_sha} differs from expected; re-downloading"
fi

log "downloading ${NIST_FIXTURE_URL} → ${DEST_FILE}"
curl -fsSL --retry 3 --retry-delay 2 --max-time 300 \
  "${NIST_FIXTURE_URL}" -o "${DEST_FILE}.tmp"

mv "${DEST_FILE}.tmp" "${DEST_FILE}"

got_sha="$(sha256sum "${DEST_FILE}" | awk '{print $1}')"
if [[ -n "${NIST_FIXTURE_SHA256:-}" ]] && [[ "${got_sha}" != "${NIST_FIXTURE_SHA256}" ]]; then
  log "ERROR: downloaded sha mismatch."
  log "  expected: ${NIST_FIXTURE_SHA256}"
  log "  got:      ${got_sha}"
  rm -f "${DEST_FILE}"
  exit 1
fi

# Cheap magic-byte sanity check — EVTX files start with the exact 8 bytes
# "ElfFile\0". `od -An -c` renders the trailing null as the literal `\0`
# token; we require it explicitly so a file that happens to start with
# "ElfFile" but is not a real EVTX (e.g. a stub HTML page named .evtx
# or a different binary format) cannot pass.
head -c 8 "${DEST_FILE}" | od -An -c | tr -d ' \n' | grep -q 'ElfFile\\0' || {
  log "ERROR: ${DEST_FILE} does not start with EVTX magic bytes (\"ElfFile\\0\")"
  log "  got: $(head -c 8 "${DEST_FILE}" | od -An -c)"
  log "  the URL likely served HTML or a redirect page, not the .evtx file."
  rm -f "${DEST_FILE}"
  exit 1
}

# Record provenance for reproducibility.
size_bytes="$(wc -c < "${DEST_FILE}")"
fetched_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "${PROV_FILE}" <<EOF
# Provenance for ${DEST_FILE}
#
# This file is auto-generated by scripts/fetch-nist-fixture.sh.
# It exists so a reviewer can answer "where did this fixture come from?"
# without consulting CI logs.

source_url:    ${NIST_FIXTURE_URL}
sha256:        ${got_sha}
size_bytes:    ${size_bytes}
fetched_at:    ${fetched_at}
fetched_by:    scripts/fetch-nist-fixture.sh
EOF

log "ok: ${DEST_FILE} (sha=${got_sha}, ${size_bytes} bytes)"
log "provenance: ${PROV_FILE}"
