#!/usr/bin/env python3
"""path-existence-smoke - assert every backtick-quoted path in operator-
facing docs resolves to a real file or directory.

Two iterations of the path-existence audit shape (commits 5e01954,
385c867) caught 7 broken file-path references across 9 files
(crypto/audit.py vs audit_log.py; goldens/...
vs goldens/.../expected-findings.json; etc.). Each was a doc
claiming a path exists that doesn't - a SANS judge or contributor
following the citation would hit a 404. This smoke locks the
audit so future contributors can't silently re-introduce the same
shape.

For each operator-facing doc in the SCAN_LIST, extract every
backtick-quoted string of the form ``path/with/at/least/one/slash``
and check that it resolves to a real file or directory. Resolution
is tried in order: relative to the doc's own dir; relative to repo
root; for service READMEs, also relative to the service's package
dir (e.g. services/agent/README.md mentioning ``crypto/audit_log.py``
should resolve at services/agent/findevil_agent/crypto/audit_log.py).

A defined ALLOW_PATTERNS list captures the false-positive shapes the
manual audits had to skip past:
  * URLs (http://, https://, mailto:)
  * MCP wire-format identifiers (tools/list, tools/call)
  * Runtime user dirs (~/.claude/, ~/hayabusa/...)
  * Install paths in decision runbooks (/usr/bin/, /usr/share/)
  * Deferred-per-A2 widget paths (apps/mcp-widgets/)
  * Dropped-per-A2 modules deliberately quoted in docs
    (findevil_agent/cli.py + 4 siblings)
  * Future-tense fixture files (fixtures/sha256sums.txt etc -
    generated by scripts/fetch-fixtures.sh at first download)
  * Conventional shorthand (`.LOG1` / `.LOG2`)

Wall-clock: ~30ms (a few hundred regex matches + Path.exists()
calls). Wired into docker/l1-compose.yml after divergence-smoke
as the 8th L1 smoke.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Operator-facing docs to scan.  Discovery is glob-based for the
# canonical doc directories so new files dropped under docs/,
# docs/runbooks/, agent-config/, and services/*/README.md are
# auto-gated without a manual SCAN_LIST update.  Plus three
# explicit root-level entries (CLAUDE.md, README.md, QUICKSTART.md)
# that aren't under any of those dirs.  EXPLICIT_DOCS captures the
# load-bearing root docs; GLOB_PATTERNS captures the dir-scoped
# auto-discovery.
EXPLICIT_DOCS: tuple[str, ...] = (
    "CLAUDE.md",
    "README.md",
    "INSTALL.md",
    "CONTRIBUTING.md",
    "QUICKSTART.md",
)

GLOB_PATTERNS: tuple[str, ...] = (
    # Canonical analyst-facing deep-dives + DATASET.md.
    "docs/*.md",
    # Decision runbooks + ci-smoke-checklist.
    "docs/runbooks/*.md",
    # Runtime DFIR agent identity (loaded by Claude Code at session
    # start per CLAUDE.md "Agent investigation prompt").
    "agent-config/*.md",
    # Per-service READMEs (one per service/* subdir).
    "services/*/README.md",
)

# Specific files that match a GLOB but should be excluded.
GLOB_EXCLUDES: frozenset[str] = frozenset()

# Service README -> the package directory under it.  Used for the
# "package-relative" resolution attempt on service READMEs (e.g.
# services/agent/README.md mentioning ``crypto/audit_log.py``
# resolves at services/agent/findevil_agent/crypto/audit_log.py).
SERVICE_PACKAGE_DIRS: dict[str, str] = {
    "services/agent/README.md": "services/agent/findevil_agent",
    "services/agent_mcp/README.md": "services/agent_mcp/findevil_agent_mcp",
    "services/mcp/README.md": "services/mcp/src",
}

# Allow-listed path patterns that look like paths but aren't files
# in this repo.  A path matching ANY of these is skipped.
ALLOW_PATTERNS: tuple[re.Pattern[str], ...] = (
    # URLs.
    re.compile(r"^(https?|mailto|ftp|data):"),
    # Anchored URLs without scheme.
    re.compile(r"^//"),
    # Protocol-Sift example paths in CLAUDE.md's appendix.
    re.compile(r"^\./(analysis|exports)/"),
    # Runtime user dirs.
    re.compile(r"^~/"),
    # Operator-created Claude Code config the operator writes to opt into the
    # optional OS-level deny-hook (docs/architecture.md, docs/sandbox/...); it
    # is intentionally NOT shipped in the repo, so it must not be asserted to
    # exist on disk.
    re.compile(r"^\.claude/settings(\.local)?\.json$"),
    # Env-var-substituted runtime paths (e.g.
    # `$XDG_STATE_HOME/findevil/memory.sqlite`,
    # `$HOME/.local/state/findevil/memory.sqlite` in agent-config/AGENTS.md
    # describing where the cross-case memory SQLite resolves at runtime).
    re.compile(r"^\$[A-Z_]+/"),
    # Install / system paths in decision runbooks + protocol-sift
    # appendix examples.  /mnt covers the SIFT VM shared-folder evidence
    # mount (`/mnt/hgfs/evidence/...`) referenced in README/QUICKSTART —
    # a guest-side runtime path, not a repo file.
    re.compile(r"^/(usr|etc|var|opt|dev|proc|sys|home|mnt)/"),
    # Runtime temp output (e.g. `/tmp/find-evil-preview.mp4`, the
    # Remotion preview path in CLAUDE.md §0.3) — generated at runtime,
    # never a repo file.
    re.compile(r"^/tmp/"),
    # Evidence drop dir. evidence/*.evtx (etc.) are gitignored runtime
    # inputs the user supplies (README/CLAUDE/QUICKSTART name
    # `evidence/DE_1102_security_log_cleared.evtx`). Not repo files.
    re.compile(r"^/?evidence/"),
    # Cargo build artifacts (`target/release/findevil-mcp`) — produced
    # by `cargo build`, gitignored, present only after a build.
    re.compile(r"^(?:[\w./-]+/)?target/(debug|release)/"),
    # MCP wire-format identifiers (tools/list, tools/call) -
    # JSON-RPC method names, not file paths.
    re.compile(r"^tools/(list|call)$"),
    # npm/pnpm scoped package names (e.g. `@findevil/web`,
    # `@tailwindcss/postcss`) — the `@scope/name` syntax uses `/`
    # the same way scoped npm packages have done since 2014, but
    # they're package identifiers, not filesystem paths. Quoted
    # in CLAUDE.md "Commands" section + apps/web/README.md for
    # `pnpm --filter` invocations.
    re.compile(r"^@[a-z0-9_-]+/[a-z0-9_-]+$"),
    # Deferred-per-Amendment-A2 widget paths. apps/web is live now,
    # so broken apps/web references should fail this smoke.
    re.compile(r"^apps/mcp-widgets(/|$)"),
    # Future-deployment paths from Amendment A4 (Managed Agents
    # production runtime).  A4 is purely additive future work, not on
    # the hackathon critical path; these are paths the implementation
    # WILL create when adopted by an organization wanting hosted
    # durability.  (The A4 design doc was removed in the 2026-06-07
    # docs cleanup; these allow-patterns remain for any lingering refs.)
    re.compile(r"^services/mcp_http(/|$)"),
    re.compile(r"^services/managed_agent(/|$)"),
    re.compile(r"^scripts/find-evil-managed$"),
    # Dropped-per-Amendment-A2 modules deliberately quoted in
    # docs to document what was removed (the L0 amendment-a2-
    # guard fails CI on their return).
    re.compile(
        r"^(?:services/agent/)?findevil_agent/(graph|api|cli|"
        r"supervisor|specialists)\.py$"
    ),
    re.compile(r"^(?:services/agent/)?findevil_agent/specialists$"),
    # Cut-per-PR-#4 packaging script, deliberately quoted in
    # docs/runbooks/dockerfile-a2-decision.md (the resolved-decision
    # record) and CLAUDE.md "Spec/code divergences" §3 to document
    # what the A2 cleanup removed.  Same pattern as the dropped-A2
    # modules above.
    re.compile(r"^scripts/build-deb\.sh$"),
    # Dropped-per-Amendment-A5 OpenTimestamps wrapper, deliberately
    # quoted in CLAUDE.md, services/agent/README.md, and the product
    # spec to document what was removed.  Same pattern as the
    # dropped-A2 modules above.  Matches both the bare shape
    # (`crypto/ots.py`) used in README.md and the fully-qualified
    # path (`services/agent/findevil_agent/crypto/ots.py`) used in
    # CLAUDE.md.
    re.compile(r"^(?:services/agent/findevil_agent/)?crypto/ots\.py$"),
    # Dropped-per-Amendment-A6 build swarm: the swarm subsystem and its
    # scripts/docker were deleted 2026-06-07.  CLAUDE.md, docs/README.md,
    # and CHANGELOG.md deliberately quote the removed paths to document
    # what was removed.  Same pattern as the dropped-A2/A5 modules above.
    re.compile(r"^services/swarm(?:/.*)?$"),
    re.compile(r"^scripts/swarm-(?:start|status)\.sh$"),
    re.compile(r"^scripts/autonomous-loop(?:[.-][a-z]+)*\.(?:py|sh)$"),
    re.compile(r"^docker/swarm-postgres\.yml$"),
    # Future-tense fixture files - generated by
    # scripts/fetch-fixtures.sh at first download per Spec #3 §5
    # and scripts/fetch-nist-fixture.sh's provenance recording.
    re.compile(r"^fixtures/sha256sums\.txt$"),
    re.compile(r"^fixtures/single-evtx/PROVENANCE\.txt$"),
    # The Security.evtx itself, also fetched by
    # scripts/fetch-nist-fixture.sh on first download.
    re.compile(r"^fixtures/single-evtx/Security\.evtx$"),
    re.compile(r"^goldens/sans-starter/"),
    # OTRF Security-Datasets external repo paths quoted in
    # DATASET.md to identify which subtrees ship the EVTX
    # fixtures we use - those paths exist in the OTRF repo,
    # not this one.
    re.compile(r"^datasets/atomic/(windows|linux)/"),
    # Windows event-log channel names that look like paths (e.g.
    # `Microsoft-Windows-PowerShell/Operational`).
    re.compile(r"^Microsoft-Windows-"),
    # GitHub Actions reference (actions/cache, actions/checkout).
    re.compile(r"^actions/[a-z-]+$"),
    # External tool plugin/rules dirs commonly cited but not
    # in this repo.
    re.compile(r"^(?:[a-z][a-z0-9_-]*/)?(?:rules|signatures)/?$"),
    # Branch / git ref names quoted with slashes.
    re.compile(r"^chore/"),
    # State files written at runtime, not committed.
    re.compile(r"^state/"),
    # Per-case run output dirs written at runtime by find-evil-auto
    # / fleet_investigate.py - tmp/auto-runs/<ts>/ and tmp/fleet-runs/<ts>/.
    # tmp/ is gitignored.
    re.compile(r"^tmp/"),
    # Optional release asset downloaded by devpost-submit.yml.
    # readiness-packet.zip is produced by scripts/readiness-gate.ps1 when an
    # operator attaches the expert-review packet; it is deliberately not
    # committed.
    re.compile(r"^release-assets/readiness-packet\.zip$"),
    # Runtime output dir (`./out/`, `./out`): gitignored and created at run time,
    # so it exists only after a run, never in the CI checkout.
    re.compile(r"^\./out(/|$)"),
    # Generated demo video: built by scripts/make-demo-video.sh and hosted on the
    # GitHub Release (not committed, to keep the clone small). CHANGELOG/docs cite
    # its generator output path; README links the hosted copy.
    re.compile(r"^docs/find-evil-demo\.mp4$"),
    # Historical release-support files removed from the source checkout in the
    # reduced public surface. References are retained in older docs as historical
    # context; current reproducibility lives in docs/release-evidence/ plus the
    # scripts/goldens that rerun those cases.
    re.compile(r"^(?:docs/)?sample-run(/|$)"),
    re.compile(r"^(?:docs/)?reports(/|$)"),
    re.compile(r"^reports/"),
    re.compile(r"^docs/plans(/|$)"),
    re.compile(r"^docs/specs(/|$)"),
    re.compile(r"^docs/templates(/|$)"),
    re.compile(r"^docs/legacy(/|$)"),
    re.compile(r"^docs/(?:demo-script-a2|divergences-resolved|onboarding)\.md$"),
    re.compile(r"^(?:docs/)?runbooks/obsidian-mind-memory\.md$"),
    re.compile(r"^\.agents/"),
    # Research-only repo-root dir for external SDK / OpenClaw / Hermes
    # / Pixel-Agents reference clones (CLAUDE.md "External reference
    # clones" + Amendment A3 §1.3).  /git-hub-references/ is gitignored
    # so it never enters the submission tree.
    re.compile(r"^git-hub-references(/|$)"),
    # n8n automation reference clones (`n8n-references/n8n/LICENSE.md`, etc.)
    # quoted in docs/runbooks/n8n-automation-integration.md.  /n8n-references/
    # is gitignored (optional, never bundled — n8n is fair-code and not part of
    # the audit chain), so its paths exist on a developer's disk but not in the
    # CI checkout.  Same shape as the git-hub-references/ external-clone allowance.
    re.compile(r"^n8n-references(/|$)"),
    # Optional operator memory vault.
    # /obsidian-mind/brain/ (Gotchas, Patterns, Key Decisions, North Star) is
    # gitignored BY DESIGN — .gitignore marks it "private and must NEVER be
    # published".
    # These examples may appear in local-operator docs but never enter the CI checkout. Same shape as the
    # git-hub-references/ + n8n-references/ gitignored-clone allowances.
    re.compile(r"^obsidian-mind/brain/"),
    # User-level Claude Code auto-memory dir.  CLAUDE.md references
    # `memory/project_autonomous_queue.md` which actually lives at
    # `~/.claude/projects/<project>/memory/...`, not at repo root.
    re.compile(r"^memory/"),
    # External open-source project short paths (GitHub org/repo format).
    # teamdfir/protocol-sift is an external competitor repo quoted in
    # docs to explain the coexistence story.  It is not a path in this repo.
    re.compile(r"^teamdfir/"),
    # The project's own GitHub repo URL + slug — canonical `verdict-dfir` and the
    # superseded `sans-hackathon`, quoted in CLAUDE.md / docs.  External GitHub
    # references, not filesystem paths in this repo.
    re.compile(r"^github\.com/TimothyVang/"),
    re.compile(r"^TimothyVang/(verdict-dfir|sans-hackathon|dev-verdict-github)"),
    # In-repo markdown anchor links (file.md#section-name).  The path-
    # existence smoke resolves file paths by their prefix up to '#'; the
    # anchor part is not a file system component.  These are allowed so
    # that cross-file anchor links don't trip the smoke.
    re.compile(r"^docs/[a-z][a-zA-Z0-9_/-]*\.md#"),
    # MIME / content types (e.g. `text/html`, `application/json`) quoted in
    # docs/onboarding.md + runbooks — HTTP media types, not file paths.
    re.compile(
        r"^(?:text|application|image|audio|video|multipart|font)/[A-Za-z0-9.+-]+$"
    ),
    # SANS SIFT OVA download host quoted in docs/onboarding.md
    # (`sansorg.egnyte.com/dl/<token>`) — an external Egnyte share URL written
    # without a scheme, not a repo path. See the SIFT setup notes.
    re.compile(r"^sansorg\.egnyte\.com/"),
    # Disk-image file-extension examples written as a pair (e.g. `.dd/.E01`) in
    # docs/DATASET.md — extension shorthand, not a filesystem path.
    re.compile(r"^\.[A-Za-z0-9]+/\.[A-Za-z0-9]+$"),
    # Operator memory-vault notes (`brain/Memories.md`, etc.) are paths inside
    # the operator's separate vault, not this repo. Same shape as
    # the git-hub-references external-clone allowance above.
    re.compile(r"^brain/"),
    # Placeholder paths that carry a literal ellipsis (U+2026), e.g.
    # Placeholder paths with an operator vault prefix and a literal ellipsis
    # mean "and so on" — a real file
    # can never contain it, so any such token is illustrative, not a path.
    re.compile(r".*…"),
)

DOC_SCOPED_ALLOW_PATTERNS: dict[str, tuple[re.Pattern[str], ...]] = {
    # Internal competitive research quotes GitHub repo slugs (`owner/repo`).
    # Those are external identifiers, not repo-local paths.
    "docs/competitive-analysis.md": (re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$"),),
}

# Compile once.  PATH_RE matches any backtick-quoted token that
# contains at least one slash.
PATH_RE = re.compile(r"`([^`\s]+/[^`\s]+)`")

OK = "[OK  ]"
FAIL = "[FAIL]"


def _is_path_shape(target: str) -> bool:
    """True if target *looks* like a candidate file/dir reference.
    Filters out tool-arg shapes, glob patterns, and other obviously-
    not-a-path strings before we even try to resolve."""
    if any(c in target for c in "*?[]{}<>="):
        return False
    if "|" in target:
        return False
    # foo:bar where bar isn't a known file extension is probably
    # an arg shape (e.g. `case_id:str`, not `path:line`).
    if ":" in target and not any(
        target.endswith(ext)
        for ext in (
            ".md",
            ".py",
            ".rs",
            ".sh",
            ".toml",
            ".yml",
            ".yaml",
            ".json",
            ".txt",
            ".deb",
            ".evtx",
            ".log",
            ".jsonl",
            ".html",
            ".pdf",
            ".png",
        )
    ):
        return False
    return True


def _is_allowed(target: str, doc: str) -> bool:
    """True if target matches one of the known false-positive
    shapes the audit should skip."""
    if any(p.match(target) for p in ALLOW_PATTERNS):
        return True
    return any(p.match(target) for p in DOC_SCOPED_ALLOW_PATTERNS.get(doc, ()))


def _resolve(doc: str, target: str) -> Path | None:
    """Try resolution attempts in order. Returns the resolved
    Path if any of them exists, else None."""
    src_dir = (REPO / doc).parent
    candidates = [
        src_dir / target,
        REPO / target,
    ]
    if doc in SERVICE_PACKAGE_DIRS:
        candidates.append(REPO / SERVICE_PACKAGE_DIRS[doc] / target)
    for c in candidates:
        try:
            if c.exists():
                return c
        except OSError:
            continue
    return None


def _discover_docs() -> list[str]:
    """Return the sorted list of repo-relative doc paths to scan.
    Combines EXPLICIT_DOCS with GLOB_PATTERNS, minus GLOB_EXCLUDES.
    Glob-based so a new doc dropped under docs/, docs/runbooks/,
    agent-config/, or services/*/ is auto-gated next CI run."""
    seen: set[str] = set()
    for d in EXPLICIT_DOCS:
        if (REPO / d).exists():
            seen.add(d)
    for pat in GLOB_PATTERNS:
        for p in REPO.glob(pat):
            if not p.is_file():
                continue
            rel = p.relative_to(REPO).as_posix()
            if rel in GLOB_EXCLUDES:
                continue
            seen.add(rel)
    return sorted(seen)


def main() -> int:
    print("=" * 60)
    print("Find Evil! - path-existence-smoke")
    print("=" * 60)

    docs = _discover_docs()
    missing = []
    total_paths = 0
    for doc in docs:
        p = REPO / doc
        # _discover_docs only yields existing files; no need to
        # re-check existence here.

        text = p.read_text(encoding="utf-8")
        for m in PATH_RE.finditer(text):
            target = m.group(1).rstrip(".,;:?")
            if not _is_path_shape(target):
                continue
            if _is_allowed(target, doc):
                continue
            total_paths += 1
            resolved = _resolve(doc, target)
            if resolved is None:
                line_no = text[: m.start()].count("\n") + 1
                missing.append((f"{doc}:{line_no}", target))

    print(f"checked {total_paths} backtick-quoted paths across {len(docs)} docs")
    print()

    if missing:
        for src, target in missing:
            print(f"{FAIL} {src}: {target!r}")
        print()
        print("=" * 60)
        print(f"FAIL - {len(missing)} broken path reference(s).")
        print("To fix: either correct the path or, if it's a")
        print("legitimate exception (e.g. a runtime install path,")
        print("a deferred-per-A2 future surface, or a")
        print("documented-and-quoted dropped module), add it to")
        print("ALLOW_PATTERNS in scripts/path-existence-smoke.py")
        print("with a one-line justification comment.")
        print("=" * 60)
        return 1

    print("=" * 60)
    print(f"OK - all {total_paths} path references resolve cleanly.")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    sys.exit(main())
